# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 181)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 211, 181))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.car_display = QtWidgets.QLabel(self.groupBox)
        self.car_display.setGeometry(QtCore.QRect(0, 20, 210, 160))
        self.car_display.setText("")
        self.car_display.setObjectName("car_display")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 0, 129, 181))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.table_distance = QtWidgets.QTableWidget(self.groupBox_2)
        self.table_distance.setGeometry(QtCore.QRect(0, 20, 128, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.table_distance.setFont(font)
        self.table_distance.setObjectName("table_distance")
        self.table_distance.setColumnCount(2)
        self.table_distance.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table_distance.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_distance.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_distance.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_distance.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_distance.setHorizontalHeaderItem(1, item)
        self.table_distance.horizontalHeader().setDefaultSectionSize(55)
        self.table_distance.verticalHeader().setDefaultSectionSize(18)
        self.table_distance.verticalHeader().setMinimumSectionSize(21)
        self.btn_debug = QtWidgets.QCheckBox(self.groupBox_2)
        self.btn_debug.setGeometry(QtCore.QRect(60, 0, 87, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_debug.setFont(font)
        self.btn_debug.setObjectName("btn_debug")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CarDetect"))
        self.groupBox.setTitle(_translate("MainWindow", "CAR_IMAGE"))
        self.groupBox_2.setTitle(_translate("MainWindow", "DIS"))
        item = self.table_distance.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_distance.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_distance.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_distance.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "distance"))
        item = self.table_distance.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "state"))
        self.btn_debug.setText(_translate("MainWindow", "Debug"))
